AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3BucketArtifactStoreParameter:
    Type: String
  RepositoryIdParameter:
    Type: String
  PipelineRoleArnParameter:
    Type: String
  GitBranchParameter:
    Type: String
  ConnectionArnParameter:
    Type: String
  GitRepoNameParameter:
    Type: String
  CodeBuildProjectNameParameter:
    Type: String
  DeploymentProjectNameParameter:
    Type: String
Resources:
  BuildPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref S3BucketArtifactStoreParameter
      Name: !Sub '${GitRepoNameParameter}-${GitBranchParameter}-build'
      RestartExecutionOnUpdate: false
      RoleArn: !Ref PipelineRoleArnParameter
      Stages:
        - Name: Checkout
          Actions:
            - Name: Checkout
              InputArtifacts: []
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref ConnectionArnParameter
                FullRepositoryId: !Ref RepositoryIdParameter
                BranchName: !Ref GitBranchParameter
              OutputArtifacts:
                - Name: sourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProjectNameParameter
                PrimarySource: sourceCode
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: artifact
        - Name: Deployment
          Actions:
            - Name: Approval
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Provider: Manual
                Version: '1'
              RunOrder: 1
            - Name: Deploy
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref DeploymentProjectNameParameter
                PrimarySource: sourceCode
              InputArtifacts:
                - Name: sourceCode
              OutputArtifacts:
                - Name: deployed
              RunOrder: 2
      Tags:
        - Key: Automated
          Value: true
