version: 0.2
env:
  shell: "bash"
phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.9
  pre_build:
    commands:
      - cp ./cicd/settings.xml ~/.m2/
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain development-artifact-repo --domain-owner 627739073141 --query authorizationToken --output text` && sed -i "s/env.CODEARTIFACT_AUTH_TOKEN/$CODEARTIFACT_AUTH_TOKEN/g" ~/.m2/settings.xml
  build:
    commands:
      - mvn install
  post_build:
    commands:
      - mvn deploy -DskipTests
