version: 0.2
env:
  shell: "bash"
phases:
  install:
    runtime-versions:
      java: corretto11
      python: 3.9
    commands:
      - sudo apt update && sudo apt install maven
  build:
    commands:
      - mvn install
